import type { Language } from "./types";

export const STORAGE_KEYS = {
  lang: "julian-reynoso-portfolio-lang-v2",
  theme: "julian-reynoso-portfolio-theme-v2",
} as const;

export const translations = {
  es: {
    navAbout: "Sobre mí",
    navWork: "Portfolio",
    navContact: "Contacto",
    theme: "Dark",
    adminMode: "Modo Administrador",
    logout: "Logout",
    login: "Login",
    heroRole: "Narrador visual y artista",
    heroSubtitle: "Narrativa visual con energía, personajes expresivos y mundos oscuros construidos cuadro por cuadro.",
    viewPortfolio: "Ver portfolio",
    aboutTitle: "Sobre mí",
    aboutBody:
      "Julian Reynoso desarrolla piezas visuales con presencia narrativa, expresión y carácter. Su trabajo combina composición, personajes, color intenso y atmósferas oscuras para construir imágenes que se sienten como escenas dentro de una historia más grande.",
    workTitle: "Portfolio",
    workSubtitle:
      "Una selección curada de narrativa visual, personajes, estudios y piezas con identidad propia.",
    collabTitle: "Colaboración",
    collabLabel: "Actitud, volumen y presencia",
    collabBody:
      "Un portfolio visual pensado para mostrar a Julian como creador expresivo: intenso, versátil y listo para propuestas editoriales, proyectos narrativos, arte de concepto y piezas de imagen con carácter.",
    skillsTitle: "Habilidades",
    contactTitle: "Contacto",
    contactSubtitle: "Disponible para proyectos visuales, editoriales, arte narrativo y colaboraciones creativas.",
    locationLabel: "Ubicación",
    location: "Mexico",
    collabsLabel: "Colaboraciónes",
    collabs: "Abiertas",
    paletteLabel: "Paleta de color",
    techniqueLabel: "Dirección",
    colorsLabel: "Colores",
    footerCollaboration: "Colaboración",
    footerRights: "Todos los derechos reservados.",
    loading: "Cargando proyectos...",
    empty: "Todavia no hay proyectos publicados.",
    edit: "Editar",
    delete: "Eliminar",
    add: "Agregar proyecto",
    save: "Guardar proyecto",
    cancel: "Cancelar",
    projectUrl: "Ver proyecto",
    githubUrl: "GitHub",
    loginTitle: "Acceso administrador",
    loginSubtitle: "Inicia sesión para gestionar el contenido del portfolio.",
    email: "Email",
    password: "Password",
    signIn: "Entrar",
    back: "Volver al portfolio",
  },
  en: {
    navAbout: "About",
    navWork: "Portfolio",
    navContact: "Contact",
    theme: "Dark",
    adminMode: "Admin Mode",
    logout: "Logout",
    login: "Login",
    heroRole: "Visual Storyteller & Artist",
    heroSubtitle: "Visual narrative with energy, expressive characters, and dark worlds built panel by panel.",
    viewPortfolio: "View portfolio",
    aboutTitle: "About",
    aboutBody:
      "Julian Reynoso develops visual pieces with narrative presence, expression, and character. His work blends composition, characters, intense color, and dark atmospheres to build images that feel like scenes inside a larger story.",
    workTitle: "Portfolio",
    workSubtitle:
      "A curated selection of visual narrative, characters, studies, and identity-driven pieces.",
    collabTitle: "Collaboration",
    collabLabel: "Attitude, Volume & Presence",
    collabBody:
      "A visual portfolio built to present Julian as an expressive creator: intense, versatile, and ready for editorial work, narrative projects, concept art, and image-led pieces with character.",
    skillsTitle: "Skills",
    contactTitle: "Contact",
    contactSubtitle: "Available for visual projects, editorials, narrative art, and creative collaborations.",
    locationLabel: "Location",
    location: "Mexico",
    collabsLabel: "Collaborations",
    collabs: "Open",
    paletteLabel: "Color palette",
    techniqueLabel: "Direction",
    colorsLabel: "Colors",
    footerCollaboration: "Collaboration",
    footerRights: "All rights reserved.",
    loading: "Loading projects...",
    empty: "No projects have been published yet.",
    edit: "Edit",
    delete: "Delete",
    add: "Add project",
    save: "Save project",
    cancel: "Cancel",
    projectUrl: "View project",
    githubUrl: "GitHub",
    loginTitle: "Admin access",
    loginSubtitle: "Sign in to manage portfolio content.",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    back: "Back to portfolio",
  },
} satisfies Record<Language, Record<string, string>>;

export const categoryLabels = {
  es: {
    all: "Todo",
    portrait: "Retrato",
    editorial: "Editorial",
    lifestyle: "Lifestyle",
    studio: "Estudio",
    details: "Detalles",
    series: "Series",
  },
  en: {
    all: "All",
    portrait: "Portrait",
    editorial: "Editorial",
    lifestyle: "Lifestyle",
    studio: "Studio",
    details: "Details",
    series: "Series",
  },
} as const;

export const skills = {
  es: ["Narrativa visual", "Comic art", "Personajes", "Color", "Composición", "Arte conceptual", "Editorial"],
  en: ["Visual Narrative", "Comic Art", "Characters", "Color", "Composition", "Concept Art", "Editorial"],
} satisfies Record<Language, string[]>;
